const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const elements=new Map(),handlers={},tools=[];
function element(){return {innerHTML:'',textContent:'',style:{},classList:{toggle(){},remove(){}},focus(){},setSelectionRange(){},matches(){return false;}};}
const fixture={today:'2026-09-17',day:'2026-09-17',server_time:'2026-09-17T10:00:00Z',ai_ready:false,settings:{coding_limit:3,admin_limit:1,total_limit:4,daily_minutes:480,timezone:'Asia/Kolkata',repo_path:'',ai_model:'gemini-2.5-flash'},tasks:[{id:1,title:'<script>unsafe</script>',description:'test',category:'coding',status:'done',priority:'high',difficulty:'hard',duration_days:2,estimate_minutes:60,original_estimate_minutes:90,actual_seconds:3600,first_started_at:'2026-09-17T08:00:00Z',finished_at:'2026-09-17T10:00:00Z',archived:0}],plans:[{task_id:1,position:0,estimate_minutes:90}],sessions:[{task_id:1,started_at:'2026-09-17T08:00:00Z',ended_at:'2026-09-17T09:00:00Z'},{task_id:2,started_at:'2026-09-17T08:30:00Z',ended_at:'2026-09-17T09:30:00Z'}],events:[]};
const report={kind:'daily',start:'2026-09-17',end:'2026-09-17',timezone:'Asia/Kolkata',generated_at:'2026-09-17T10:00:00Z',finalized:false,summary:{planned:1,completed:0,carried_forward:1,task_seconds:60,active_seconds:60,estimate_ratio:null},tasks:[]};
const calls=[];
const sandbox={console,Date,Intl,URL,Blob,AbortController,setTimeout:()=>1,clearTimeout(){},setInterval(){},addEventListener(){},document:{activeElement:null,querySelector(s){if(s==='dialog[open]')return null;if(!elements.has(s))elements.set(s,element());return elements.get(s);},querySelectorAll(){return [];},addEventListener(n,fn){handlers[n]=fn;},modelContext:{registerTool(t){tools.push(t);}}},fetch:async(path,options)=>{calls.push({path,options});return {ok:true,json:async()=>path.includes('/create')?{ok:true,id:2}:path.includes('/report?')?structuredClone(report):structuredClone(fixture)};}};
vm.createContext(sandbox);vm.runInContext(fs.readFileSync('static/app.js','utf8'),sandbox);
(async()=>{
  await new Promise(r=>setImmediate(r));
  for(const name of ['today','inbox','all','insights','activity','settings','reports','communications','trash']){vm.runInContext(`navigate('${name}')`,sandbox);assert.ok(elements.get('#view').innerHTML.length>100,`${name} rendered`);assert.ok(!elements.get('#view').innerHTML.includes('<script>unsafe</script>'),'user input escaped');}
  await new Promise(r=>setImmediate(r));
  vm.runInContext("navigate('today')",sandbox);
  assert.ok(elements.get('#view').innerHTML.includes('inbox-rail'),'My Day inbox rail exists');
  vm.runInContext("inboxCollapsed=true;render()",sandbox);assert.ok(elements.get('#view').innerHTML.includes('inbox-rail collapsed'),'rail collapses');
  vm.runInContext("navigate('inbox')",sandbox);assert.ok(elements.get('#view').innerHTML.includes('daily-list-panel'),'Inbox has daily plan column');
  const nav=vm.runInContext('taskNavigation(1)',sandbox);assert.ok(nav.includes('Previous task')&&nav.includes('Next task'),'task navigation arrows');
  const time=vm.runInContext('dailyTime()',sandbox);assert.equal(time.total,7200);assert.equal(time.union,5400);
  fixture.sessions=[{task_id:1,started_at:'2026-09-16T18:00:00Z',ended_at:'2026-09-16T19:00:00Z'}];await vm.runInContext('refresh()',sandbox);
  const midnight=vm.runInContext('dailyTime()',sandbox);assert.ok(Math.abs(midnight.total-1800)<.01,'session clipped at local midnight');
  const dayHtml=vm.runInContext('todayView()',sandbox);assert.ok(dayHtml.includes('1h 30m'),'planning snapshot retained in daily total');
  assert.equal(tools.length,2);const captured=await tools[1].execute({title:'A valid task'});assert.equal(captured.id,2);
  await assert.rejects(()=>tools[1].execute({title:5}),/title is required/);
  await handlers.click({target:{closest:()=>({dataset:{status:'in_progress',id:'1'},classList:{contains:()=>false}})}});
  const statusCall=calls.find(c=>c.path==='/api/status');assert.deepEqual(JSON.parse(statusCall.options.body),{id:1,status:'in_progress'});
  await vm.runInContext("dropTask(2,'plan',1)",sandbox);
  const placed=calls.find(c=>c.path==='/api/place');assert.deepEqual(JSON.parse(placed.options.body),{id:2,day:'2026-09-17',before_id:1});
  await vm.runInContext("dropTask(1,'inbox')",sandbox);assert.ok(calls.some(c=>c.path==='/api/unplan'),'drop back to inbox removes membership');
  vm.runInContext("day='2026-09-16'",sandbox);const count=calls.length;await vm.runInContext("dropTask(2,'plan')",sandbox);assert.equal(calls.length,count,'past day drop is read-only');
  vm.runInContext("day='2026-09-17';view='reports';currentReport=null",sandbox);await vm.runInContext('refresh()',sandbox);assert.ok(elements.get('#view').innerHTML.includes('Daily task record'),'daily report rendered');
  report.kind='weekly';report.start='2026-09-14';report.end='2026-09-20';report.days=[];vm.runInContext("reportKind='weekly'",sandbox);await vm.runInContext('refresh()',sandbox);assert.ok(elements.get('#view').innerHTML.includes('The week at a glance'),'weekly report rendered');
  fixture.tasks.push({...fixture.tasks[0],id:9,title:'COMMUNICATION_ONLY',kind:'communication',contact:'Reviewer',status:'waiting'});
  fixture.plans.push({task_id:9,position:1,estimate_minutes:15});
  await vm.runInContext('refresh()',sandbox);
  for(const name of ['today','inbox','all']){vm.runInContext(`navigate('${name}')`,sandbox);assert.ok(!elements.get('#view').innerHTML.includes('COMMUNICATION_ONLY'),'communications stay out of task surfaces');}
  vm.runInContext("navigate('communications')",sandbox);assert.ok(elements.get('#view').innerHTML.includes('COMMUNICATION_ONLY'));assert.ok(elements.get('#view').innerHTML.includes('Reviewer'));
  fixture.tasks.find(t=>t.id===9).status='in_progress';
  await vm.runInContext('refresh()',sandbox);
  const capacityHtml=vm.runInContext('capacity()',sandbox);
  assert.ok(capacityHtml.includes('COMMUNICATION_ONLY'),'running communications are visible alongside limits');
  assert.ok(capacityHtml.includes('Edit limits'));
  assert.ok(vm.runInContext('settingsView()',sandbox).includes('name="admin_limit"'),'admin running limit is editable');
  assert.ok(vm.runInContext('todayView()',sandbox).includes('data-drop="assigned"'),'Assigned is a board drop target');
  sandbox.assignedFixture={status:'assigned',assignee:'Team <A>',waiting_note:'Handoff ready'};
  const assignmentBadge=vm.runInContext('holdBadge(assignedFixture)',sandbox);
  assert.ok(assignmentBadge.includes('Team &lt;A&gt;'));
  assert.ok(assignmentBadge.includes('Handoff ready'));
  const commentHtml=vm.runInContext("commentsHtml([{at:state.server_time,status:'waiting',text:'<script>unsafe</script>'}],{id:1})",sandbox);
  assert.ok(commentHtml.includes('Add comment'));assert.ok(commentHtml.includes('Waiting / on hold'));assert.ok(!commentHtml.includes('<script>unsafe</script>'));
  const trackerHtml=vm.runInContext("subissuesHtml([{id:2,title:'Work <step>',kind:'task',status:'done'},{id:3,title:'Ask reviewer',kind:'communication',status:'waiting'}],{id:1})",sandbox);
  assert.ok(trackerHtml.includes('1 / 2 complete'));assert.ok(trackerHtml.includes('↔ Communication'));assert.ok(trackerHtml.includes('Work &lt;step&gt;'));assert.ok(trackerHtml.includes('data-child-move'));assert.ok(trackerHtml.includes('Add step'));
  // Browser form named properties shadow `form.id` when a field is named id.
  sandbox.FormData=class {constructor(form){return new Map(Object.entries(form.values));}};
  let closed=false;
  sandbox.document.querySelector('#task-dialog').close=()=>{closed=true;};
  const button={disabled:false};
  const editForm={id:{value:'1'},getAttribute:()=> 'task-form',values:{id:'1',title:'Renamed task',description:'Updated definition of done',estimate_minutes:'45',duration_days:'2',related_task_id:'9'},elements:{ai_enabled:{checked:false},plan_today:{checked:false}},querySelector:()=>button};
  await handlers.submit({preventDefault(){},target:editForm});
  const update=calls.find(c=>c.path==='/api/update');
  assert.ok(update,'Save changes sends an update despite the named id field');
  assert.equal(JSON.parse(update.options.body).related_task_id,9,'linked task id is numeric');
  assert.equal(JSON.parse(update.options.body).title,'Renamed task');
  assert.equal(JSON.parse(update.options.body).description,'Updated definition of done');
  assert.ok(closed,'successful save closes the editor');
  assert.equal(button.disabled,false);
  editForm.values.id='';closed=false;
  const beforeCreate=calls.filter(c=>c.path==='/api/create').length;
  await handlers.submit({preventDefault(){},target:editForm});
  assert.equal(calls.filter(c=>c.path==='/api/create').length,beforeCreate+1,'new-task save also dispatches');
  fixture.tasks=[];fixture.plans=[];fixture.sessions=[];await vm.runInContext('refresh()',sandbox);
  for(const name of ['today','inbox','all','insights','activity','settings','reports','communications','trash'])vm.runInContext(`navigate('${name}')`,sandbox);
  console.log('Frontend contracts passed: seven populated/empty views, both inbox/day surfaces, collapse, drag/drop handlers, historical protection, daily/weekly reports, escaping, timing, and WebMCP adapter contracts.');
})().catch(e=>{console.error(e);process.exitCode=1;});
